### ISSUE TITLE
Should work on methods

### ISSUE THREAD

**Issue by bestouff** [llogiq/momo#1]
I know you already intend to implement that, I'm just opening an issue to track it.

**Comment by llogiq** [comment]
Thanks. Yes, that's likely the next thing I intend to tackle.

**Comment by llogiq** [comment]
It should now work. However, there's a niggle in that if the method uses generics defined in the `impl`, we don't have the actual types. We may need to allow `#[momo]` on impl blocks so it can get the types there.

**Comment by danielhenrymantilla** [comment]
@llogiq you may have a look at [`::require_unsafe_in_body`](https://docs.rs/require_unsafe_in_body/0.1.2/require_unsafe_in_body/attr.require_unsafe_in_body.html#limitation), since that exactly what is done to tackle the `Self` issue.

**Comment by marcospb19** [comment]
Sorry for bumping an old issue, does this works on methods without generics defined in the `impl`?

I'm a beginner so sorry _if_ I'm posting a dumb noob error.

This is giving me a compilation error:
```rust
// FileType is an Enum that contains the variant File
impl FileType {
    #[momo]
    pub fn from_path(_path: impl AsRef<Path>) -> Result<Self> {
        Ok(FileType::File) // Temporary.
    }
}
```
```rust
error[E0425]: cannot find function `_from_path_inner` in this scope
  --> src/file.rs:33:5
   |
33 |     #[momo]
   |     ^^^^^^^ not found in this scope
   |
```

---

But `momo` is correctly included with `use momo::momo;`, I'm not getting the `error: cannot find attribute 'momo' in this scope` that I get by removing the include.

---

So I did this:
```rust

#[momo]
impl FileType {
    ...
}
```
And now it compiles, but there is no example showing this usage here in the repository, so is this working correctly as expected?

**Comment by Artoria2e5** [comment]
Uhhhh... on top of the watt-ifying update removing the member example, it seems to have removed some member-related code too (mainly the `has_self` thing). Maybe some mistakes were made regarding which version to port?

**Comment by bestouff** [comment]
Great thanks !
