### ISSUE TITLE
Lifetimes not supported?

### ISSUE THREAD

**Issue by dimpolo** [llogiq/momo#12]
I came accross this:

```rust
#[momo::momo]
fn bug<'a, T: Into<&'a str>>(test: T) {
    let _ = test.into();
}
```

```
error: custom attribute panicked
   = help: message: CodeTrapped(Trap { origin: LoadOutOfMemory })
```

I wouldn't mind looking into this myself if you could give me an idea where to start looking :)

**Comment by llogiq** [comment]
That's quite interesting. I must admit that I haven't worked on momo for quite some time, so I wouldn't know where to look either. I think it's likely due to generics (or my lackluster handling of them).

**Comment by dimpolo** [comment]
It seems using `momo = { git = "https://github.com/llogiq/momo.git" }` resolves this.
May I ask you to release a new version with d9c1590114470598e04e93272478bf35618580d0 included?

Two unrelated things I found, while investigating:
Inside `wasm/Cargo.toml` you might want to change these lines:
`codegen_units = 1` => `codegen-units = 1`
`proc-macro2 = "=1.0.27"     # Temporary hack as watt is left at .27`  => `proc-macro2 = "1.0"`

Thanks in advance!

**Comment by llogiq** [comment]
I'll publish a new version soon and let you know when it's done.

**Comment by llogiq** [comment]
0.2.2 is released on crates.io. Enjoy!
